const tipsCollection =  [

{tip: "Maintain Balance Before Adding Fish to a New Aquarium"},
{tip: "Decorate Your Aquarium for the Fish"},
{tip: "Don’t Worry if Your Fish Hide at First"},
{tip: "Aquarium Lighting Should Be Used to Create a Day and Night Cycle"},
{tip:`Clean Your Aquarium Regularly, Just Not Right After Setup`},
{tip:`Do Your Research Before Buying More Fish`},
{tip:"Choose an Appropriately Sized Tank"},
{tip:"Find a Place for Your Aquarium"},
{tip:"Know Your Fish"},
{tip:"Condition Your Water"},
{tip:"Cycle Your Tank"},
{tip:"Perform Regular Water Changes"},
{tip:`Don't Overstock Your Tank`},
{tip:`Do Not Overfeed Your Fish`},
{tip:`Use Caution With New Fish`},
{tip:`Use Caution With Treatments and Chemicals`},
{tip:`Don't Trust the Salesperson`},
{tip:`Join Some Aquarium Groups`},
{tip:`Be patient`},
{tip:`Stock slowly`},
{tip:`Don’t overfeed`},
{tip:`Don’t overstock`},
{tip:`Choose function over novelty`},
{tip:`Buy as big a tank as you can afford`},
{tip:`Find a good retailer`},
{tip:`Join a fish club`},
{tip:`Keep the easy stuff first`},
{tip:`Make time for maintenance`},
{tip:`Make notes`},
{tip:`Be prepared`},
{tip:`Set realistic budgets`},
{tip:`Ask questions`},
{tip:`Choose healthy fish`},
{tip:`In car travel`},
{tip:`Go straight home`},
{tip:`Acclimatise`},
{tip:`Get the right advice`},
{tip:`Buy quality kit`},
{tip:`Shop around`},
{tip:`Go smaller or bigger`},
{tip:`Check power consumption`},
{tip:`Maintain your equipment`},
{tip:`Don't overcomplicate`},
{tip:`Get a light timer`},
{tip:`Test water`},
{tip:`Isolate`},
{tip:`Seek expert advice`}
];

export const getTips = () => {
	
	return tipsCollection;
}